name: 🧩 Thrylo Labs Issue Templates
description: Choose the right template to report bugs or suggest new features.
title: "[Issue]: "
labels: []

# These links will appear under "Contact Links" in the issue chooser
contact_links:
  - name: 📣 Community Discussions
    url: https://github.com/thrylolabs/.github/discussions
    about: Use our discussion board for general questions or brainstorming ideas.
