name: 🧩 Thrylo Labs Issue Templates
description: Choose the appropriate template to report a bug, suggest a feature, or raise a custom issue.
blank_issues_enabled: false

contact_links:
  - name: 📣 Community Discussions
    url: https://github.com/thrylolabs/.github/discussions
    about: For general questions, brainstorming, or open-ended feedback.

